# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('super', 'super')], default='student', max_length=8),
        ),
    ]
