# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0005_announcements_exampapes_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='ExamPapers/')),
                ('term', models.CharField(choices=[('M', 'mid-term'), ('E', 'end-term')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.RemoveField(
            model_name='exampapes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exampapes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_no',
        ),
        migrations.DeleteModel(
            name='ExamPapes',
        ),
        migrations.AddField(
            model_name='exampapers',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exampapers',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assist.Course'),
        ),
    ]
