# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0006_auto_20170226_0158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
