# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0007_auto_20170226_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.AddField(
            model_name='exampapers',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
