# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0008_auto_20170226_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPapers',
            new_name='ExamPaper',
        ),
    ]
