# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0010_auto_20170226_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='term',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
