# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0012_auto_20170226_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assist.Course')),
            ],
        ),
    ]
