# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0013_courseallotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallotment',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist.Course'),
        ),
    ]
