# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0015_auto_20170227_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('super', 'super')], default='student', max_length=10),
        ),
    ]
