# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0020_bookmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
    ]
